name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # обновление каждый час
  workflow_dispatch:               # ручной запуск

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # ↓ базовые секции (можно оставить пустым)
          base: ""

          # ↓ включение календаря коммитов
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
