name: GitHub Metrics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
